name: generate-animation

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: biaov
          outputs: |
            dist/snake.svg
      - name: push snake.svg to the assets branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: assets
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

